name: Reusable workflow
on: 
    workflow_call:
        inputs:
            artifact-name:
                description: This variable will hold the aritifact name which is required during deployment.
                required: false
                default: dist
                type: string
        secrets: #There is no default value in case of secrets
            some-secret:
                required: false
jobs:
    deploy:
        runs-on: ubuntu-latest
        # env:
        #     secret-variable: ${{ secrets.some-secret }}
        steps:
            - name: Download Artifact
              uses: actions/download-artifact@v4
              with:
                name: ${{ inputs.artifact-name }}
            - name: List files
              run: ls
            - name: Output information
              run: echo "Deploying and Uploading"